// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvfknfniksvgmwmtrecv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2ZmtuZm5pa3N2Z213bXRyZWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4NTQwMzcsImV4cCI6MjA3NjQzMDAzN30.WMHgEtCN6Kiq_QFzuGyEMir2t_vWKLbdzXogPQUsB_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});